### PR TITLE
feat(markdown): setext_heading

### PR DESCRIPTION
**Pull request by tomtomjhj**

### CODE REVIEW

**Review by stevearc — CHANGES_REQUESTED** [review]
Since you're adding support for more heading types, could you add them to [the test file](https://github.com/stevearc/aerial.nvim/blob/master/tests/treesitter/markdown_test.md) and update the tests?

**Comment by tomtomjhj** [comment]
Added tests, but now the custom backend test fails because it doesn't implement setext_heading.

**Comment by stevearc** [comment]
You can split the custom backend test into another file. It was only there because the functionality was equivalent, but now that it's not we can move it.

**Comment by tomtomjhj** [comment]
fixed

**Comment by stevearc** [comment]
LGTM thanks!

**Pull request merged**
