### PR TITLE
Add support for properties and fields for C# in treesitter backend

### PR DESCRIPTION
**Pull request by fnix2**
Fields and properties support.

### CODE REVIEW

**Comment by stevearc** [comment]
Awesome, thanks for the PR! Would you be able to add a an [example](https://github.com/stevearc/aerial.nvim/blob/master/tests/treesitter/csharp_test.cs) and [test](https://github.com/stevearc/aerial.nvim/blob/master/tests/treesitter/csharp_spec.lua)?

**Comment by fnix2** [comment]
I started doing it, but got confused. Could you explain how set "end_col" field in csharp_spec.lua?

**Comment by stevearc** [comment]
The way I usually do it is I add the example, guess at the numbers, then inspect the test results when they fail and double check that they make sense. If they do, I copy those values into the spec file

**Comment by fnix2** [comment]
Done

**Comment by fnix2** [comment]
Btw in my configuration neovim with ```--noplugins``` and ```-u minimal_init.lua``` couldn't invoke treesitter and plenary. I needed to add this lines to minimal_init.lua:
```
vim.cmd("call plug#begin()")
vim.cmd("Plug 'nvim-treesitter/nvim-treesitter'")
vim.cmd("Plug 'nvim-lua/plenary.nvim'")
vim.cmd("call plug#end()")
```

Maybe it will help someone.

**Comment by stevearc** [comment]
Excellent, thank you!

**Pull request merged**
