### PR TITLE
Revert window ignore → closes #369

### LINKED ISSUE #369: bug: 51a07949abf169b4cad30e14c165ac1ec0ce4e6f do not respect aerial position
### Neovim version (nvim -v)

NVIM v0.9.5 Release

### Operating system/version

arch

### Output of :AerialInfo

Aerial Info                                                                                                                                                                  
-----------                                                                                                                                                                  
Filetype: neo-tree                                                                                                                                                           
Configured backends:                                                                                                                                                         
  lsp (not supported) [No LSP client found that supports symbols]                                                                                                            
  treesitter (not supported) [No treesitter parser for neo-tree]                                                                                                             
  markdown (not supported) [Filetype is not markdown]                                                                                                                        
  man (not supported) [Filetype is not man]                                                                                                                                  
Show symbols: Constructor, Enum, Function, Interface, Method     

### Describe the bug

Opening aerial while the cursor is over NeoTree, open aerial in the wrong position.

If I open it while the cursor is over the buffer, it opens on the right position (on the right)
screenshot_2024-05-01_18-20-15_002572586

### What is the severity of this bug?

minor (annoyance)

### Steps To Reproduce

* Run `:Neotree`
* Run `:AerialOpen`

### Expected Behavior

* Opening aerial while the cursor is over NeoTree should open Aerial in the correct position.
* Ideally, with the content of the last valid targeted buffer .

### Minimal example file

_No response_

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "stevearc/aerial.nvim",
    config = function()
      require("aerial").setup({
        -- add your aerial config here
      })
    end,
  },
  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    config = function()
      require("nvim-treesitter.configs").setup({
        ensure_installed = { "c", "lua" },
        auto_install = true,
        highlight = { enable = true },
      })
    end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Zeioth**
Reverts https://github.com/stevearc/aerial.nvim/commit/51a07949abf169b4cad30e14c165ac1ec0ce4e6f

Closes: #369

### CODE REVIEW

**Comment by stevearc** [comment]
This means that the behavior would go back to not opening Aerial at all if you toggle it in the Neotree buffer. Is that a better situation than this one?

Another thing to look into: if you want aerial to stick to the right edge of your editor, you can set the options

```lua
require("aerial").setup({
  layout = {
    default_direction = "right",
    placement = "edge",
  }
})
```

Would that solve your issue?

**Comment by Zeioth** [comment]
@stevearc That solution works fine steve thank you:

## How I've tested
* I've added your options as 
```lua
      layout = {
        min_width = 28,
        default_direction = "right",
        placement = "edge",
      },
```

## Happy day scenario
I've focused neotree and opened aerial
screenshot_2024-05-06_21-40-26_072753969

It opens in the correct position, and once I click the code, aerial is populated correctly
screenshot_2024-05-06_21-40-31_743902030

## Bad day scenario
It is still possible to fuck the UI when performing obscure actions such as
* Open aerial
* Open neotree (the cursor is on neotree now)
* Then try to open aerial again → That spawns a second aerial, instead of toggling the current one.
screenshot_2024-05-06_21-44-39_119683384

This is already better, but maybe I would still revert, or check that out. Up to you.

**Comment by Zeioth** [comment]
If I repeat that I can spawn infinite aerials
screenshot_2024-05-06_21-50-55_265972373

**Comment by stevearc** [comment]
@Zeioth Try setting the `attach_mode` as well
```lua
require("aerial").setup({
  layout = {
    default_direction = "right",
    placement = "edge",
  },
  attach_mode = "global"
})
```

**Comment by Zeioth** [comment]
I had it already. Full config:

```lua
{
    "stevearc/aerial.nvim",
    event = "VeryLazy",
    opts = {
      ignore = {
        buftypes = { "nofile" },
      },
      filter_kind = { -- Symbols that will appear on the tree
        -- "Class",
        "Constructor",
        "Enum",
        "Function",
        "Interface",
        -- "Module",
        "Method",
        -- "Struct",
      },
      open_automatic = false, -- Open if the buffer is compatible
      autojump = true,
      link_folds_to_tree = false,
      link_tree_to_folds = false,
      attach_mode = "global",
      backends = { "lsp", "treesitter", "markdown", "man" },
      disable_max_lines = vim.g.big_file.lines,
      disable_max_size = vim.g.big_file.size,
      layout = {
        min_width = 28,
        default_direction = "right",
        placement = "edge",
      },
      show_guides = true,
      guides = {
        mid_item = "├ ",
        last_item = "└ ",
        nested_top = "│ ",
        whitespace = "  ",
      },
      keymaps = {
        ["[y"] = "actions.prev",
        ["]y"] = "actions.next",
        ["[Y"] = "actions.prev_up",
        ["]Y"] = "actions.next_up",
        ["{"] = false,
        ["}"] = false,
        ["[["] = false,
        ["]]"] = false,
      },
    },
    config = function(_, opts)
      require("aerial").setup(opts)
      -- HACK: The first time you opened aerial on a session, close all folds.
      vim.api.nvim_create_autocmd("FileType", {
        desc = "Aerial: The first time its open on a session, close all folds.",
        callback = function()
          local is_aerial = vim.bo.filetype == "aerial"
          local is_ufo_available = require("base.utils").is_available("nvim-ufo")
          if is_ufo_available and is_aerial and vim.g.new_aerial_session == nil then
            vim.g.new_aerial_session = false
            require("aerial").tree_set_collapse_level(0, 0)
          end
        end,
      })
    end
  },
```

**Comment by stevearc** [comment]
@Zeioth I believe I've fixed the issue with multiple aerial windows opening when `attach_mode = "global"`. I think this was the last bug in this scenario, so I'm closing this PR (it seems unlikely that we would want to revert this change anyway). If there are still problems, feel free to continue the discussion on the linked issue or create a new issue

**Pull request closed without merging**
